This is the test for forward and backward algorithm along with observation possibility

In [1]:
from PattRecClasses import GaussD, HMM, MarkovChain
import numpy as np

g1 = GaussD( means=[0], stdevs=[1] )   
g2 = GaussD( means=[3], stdevs=[2] )   

xtest = np.array([-0.2, 2.6, 1.3])

The following is the block for testing infinite HMM's forward and backward function

In [2]:
#Infinite
Infinitemc = MarkovChain( np.array([1, 0]), np.array([[0.9, 0.1], [0.1, 0.9]])) 
InfiniteHMM  = HMM(Infinitemc, [g1, g2]) 
bmat = InfiniteHMM.prob(xtest, True)
alpha, c = Infinitemc.forward(bmat)
print("Infinite HMM:")
print("AlphaHat matrix:")
print(np.around(alpha, 4))
print("C value: ")
print(np.around(c, 4))
beta = Infinitemc.backward(bmat, c)
print("BetaHat matrix:")
print(np.around(beta, 4))


Infinite HMM:
AlphaHat matrix:
[[1.     0.3847 0.4591]
 [0.     0.6153 0.5409]]
C value: 
[1.     0.1625 0.8881]
BetaHat matrix:
[[1.     6.7973 1.126 ]
 [5.2223 5.7501 1.126 ]]


The following is the block for testing finite HMM's forward and backward function

In [3]:
#Finite
finitemc = MarkovChain(np.array([1, 0]), np.array([[0.9, 0.1, 0], [0, 0.9, 0.1]])) 

finiteHMM  = HMM(finitemc, [g1, g2]) 
bmat1 = finiteHMM.prob(xtest, True)
alpha1, c1 = finitemc.forward(bmat1)
print("Finite:")
print("AHat matrix:")
print(np.around(alpha1, 4))
print("C value: ")
print(np.around(c1, 4))
beta1 = finitemc.backward(bmat1, c1)
print("BetaHat matrix:")
print(np.around(beta1, 4))

Finite:
AHat matrix:
[[1.     0.3847 0.4189]
 [0.     0.6153 0.5811]]
C value: 
[1.     0.1625 0.8266 0.0581]
BetaHat matrix:
[[1.     1.0389 0.    ]
 [8.4154 9.3504 2.0818]]


The following block is the test for log function

In [4]:
bmat2 = finiteHMM.prob(xtest, False)
alpha2, c2 = finitemc.forward(bmat2)
cp = finiteHMM.logprob(c2)
print("Observation possibility for finite HMM: ", cp)
print("C value without scale",c2)
print("C value with scale", c1)

Observation possibility for finite HMM:  -9.187726979475208
C value without scale [0.39104269 0.03177681 0.14165001 0.05811253]
C value with scale [1.         0.16252347 0.82658096 0.05811253]
