This is the test for forward algorithm

In [12]:
from PattRecClasses import GaussD, HMM, MarkovChain
import numpy as np

g1 = GaussD( means=[0], stdevs=[1] )   
g2 = GaussD( means=[3], stdevs=[2] )   

xtest = np.array([-0.2, 2.6, 1.3])

In [13]:
#Nonfinite
nonfinitemc = MarkovChain( np.array([1, 0]), np.array([[0.9, 0.1], [0.1, 0.9]])) 
nonfiniteHMM  = HMM(nonfinitemc, [g1, g2]) 
bmat = nonfiniteHMM.prob(xtest, True)
alpha, c = nonfinitemc.forward(bmat)
print("Infinite:")
print("AHat matrix:")
print(np.around(alpha, 4))
print("c value: ")
print(np.around(c, 4))
beta = nonfinitemc.backward(bmat, c)
print("NonfiniteHMM:")
print("betaHat:")
print(np.around(beta, 4))


Infinite:
AHat matrix:
[[1.     0.3847 0.4591]
 [0.     0.6153 0.5409]]
c value: 
[1.     0.1625 0.8881]
NonfiniteHMM:
betaHat:
[[1.     6.7973 1.126 ]
 [5.2223 5.7501 1.126 ]]


In [14]:
#Finite
finitemc = MarkovChain(np.array([1, 0]), np.array([[0.9, 0.1, 0], [0, 0.9, 0.1]])) 

finiteHMM  = HMM(finitemc, [g1, g2]) 
bmat1 = finiteHMM.prob(xtest, True)
alpha1, c1 = finitemc.forward(bmat1)
print("Finite:")
print("AHat matrix:")
print(np.around(alpha1, 4))
print("c value: ")
print(np.around(c1, 4))
beta1 = finitemc.backward(bmat1, c1)
print("betaHat:")
print(np.around(beta1, 4))

Finite:
AHat matrix:
[[1.     0.3847 0.4189]
 [0.     0.6153 0.5811]]
c value: 
[1.     0.1625 0.8266 0.0581]
betaHat:
[[ 9.7208 20.8789  2.0818]
 [75.7384 84.1538 18.7364]]


In [15]:
#Test logprob
bmat2 = finiteHMM.prob(xtest, False)
alpha2, c2 = finitemc.forward(bmat2)
cp = finiteHMM.logprob(c2)
print("logprob: ", cp)
print(c2)

logprob:  -9.187726979475208
[0.39104269 0.03177681 0.14165001 0.05811253]
